markdown: redcarpet
highlighter: pygments

redcarpet:
  extensions: ['tables', 'autolink', 'no_intra_emphasis', 'with_toc_data', 'strikethrough']

encoding: utf-8
gems:
  - jekyll-redirect-from
  - jekyll-sitemap